services:
  smartretail_app:
    build: .
    container_name: smartretail_app
    volumes:
      - .:/app
    depends_on:
      - smartretail_db
    environment:
      - POSTGRES_DB=smartretail
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=AQh8zR2@7eCw
      - DB_HOST=smartretail_db
      - ENCRYPTION_KEY=hhNyNMWtMUKGggDvxfWBKjINrbLIszOYaT_wusdrme0=
    restart: unless-stopped

  smartretail_db:
    image: postgres:15
    container_name: smartretail_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: smartretail
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: AQh8zR2@7eCw
      APP_USER: ${APP_USER}
      APP_PASSWORD: ${APP_PASSWORD}
      ANALYST_USER: ${ANALYST_USER}
      ANALYST_PASSWORD: ${ANALYST_PASSWORD}
      WRITER_USER: ${WRITER_USER}
      WRITER_PASSWORD: ${WRITER_PASSWORD}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
    volumes:
      - smartretail_pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  smartretail_pgdata:
