{
 "title": "ALL",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Dernier nombre de lignes insérées",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "smartretail_last_insert_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nombre total d'exécutions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "smartretail_runs_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Erreurs rencontrées",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(smartretail_errors_total[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durée moyenne de traitement (1 min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(smartretail_processing_duration_seconds_sum[1m]) / rate(smartretail_processing_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}